Balance Changes for Kalimdor
AzerothWarsLR/WarcraftLegacies pull request #2210
Opened 2023-09-21 22:18 UTC by Ripzss

Bladestorm damage for Grom/Garrosh Nerfed by 10%.
Chen Drunken haze now got same values as Muradin
Voodoo Restoration Range nerfed by 10%
Grommash Hellscream Xp reward nerfed by 20%
Druid of the Talon Gold cost 14 -> 16
Druid of the Talon Hp increased 350 -> 390
Mountain Giant base armor 5 -> 6
Sentinels Archer Hp increased from 525 -> 560
Sentinels Archer base damage increased from 23 -> 25
HippoGryph Rider Base damage increased from 19 -> 20
HippoGryph Rider Base hp increased from 850 -> 900
2nd level added to Moon Glaive Locked Behind quest "Drive Them Back"

2023-09-21 23:24 UTC, YakaryBovine commented
I'll review this properly later, but I can see one thing straight away: you need to update the description for Drive Them Back to indicate the new reward.

2023-09-22 00:53 UTC, Ripzss commented
Done something wrong with the Moon Glaive level 2 research gonna fix this first

2023-09-22 06:20 UTC, YakaryBovine commented on src/WarcraftLegacies.Source/Quests/Sentinels/QuestSentinelsKillFrostwolf.cs
> +    protected override string RewardDescription => "Moon Riders are trainable at the Roost, Moon Glaive second level is now reserachable at the War Academy";
```suggestion
    protected override string RewardDescription => $"Learn to train {GetObjectName(Constants.UNIT_E022_MOON_RIDER_SENTINELS)}s from the {GetObjectName(Constants.UNIT_EDOS_ROOST_SENTINELS)}s and research {GetObjectName(Constants.UPGRADE_REMG_UPGRADE_MOON_GLAIVE_LIGHT_BLUE_RESEARCH)}'s second level from the {GetObjectName(Constants.UNIT_E00L_WAR_ACADEMY_SENTINEL_BARRACKS)}";
```

2023-09-22 06:22 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UpgradeData/Skin/1735222610.json
> +      "Value": "Causes Huntress attacks to strike an additional unit"
Huntress should be in the possessive, plural form. Upgrade descriptions are full sentences so should end with a full stop. Thus: 
```suggestion
      "Value": "Causes Huntresses' attacks to strike an additional unit."
```

2023-09-22 06:25 UTC, YakaryBovine requested changes
Couple things to fix, but looks solid otherwise.

2023-09-22 22:04 UTC, YakaryBovine approved these changes
Looks good. Thanks for the solid attention to detail on keeping the tooltip numbers up to date.

2023-09-22 22:04 UTC, merged