Settings Save/Load System
AzerothWarsLR/WarcraftLegacies pull request #2250
Opened 2023-09-25 21:28 UTC by SavanticIO

Updated WCSharp.Json and WCSharp.Shared so that WCSharp.SaveLoad could be added.

Added a save and load system using WCSharp.SaveLoad for player settings.

Added commands for toggling Dialogue, QuestText and Captions

Added a command to see current settings

2023-09-25 23:12 UTC, YakaryBovine requested changes
Really, really cool stuff. Nothing to add in terms of the code I think. I just have a handful of suggestions for tooltips. Nice work!

2023-09-25 23:12 UTC, YakaryBovine commented on src/MacroTools/Commands/Captions.cs
> +  /// A <see cref="CommandSystem.Command"/> that sets the player's camera to a specific height.
This comment refers to camera stuff.

2023-09-25 23:12 UTC, YakaryBovine commented on src/MacroTools/Commands/Captions.cs
> +        return "You must specify a boolean value(true or false) as the first parameter.";
```suggestion
        return "You must specify either true or false as the first parameter.";
```

2023-09-25 23:12 UTC, YakaryBovine commented on src/MacroTools/Commands/Dialogue.cs
> +  /// A <see cref="CommandSystem.Command"/> that sets the player's camera to a specific height.
Not the right comment.

2023-09-25 23:12 UTC, YakaryBovine commented on src/MacroTools/Commands/Dialogue.cs
> +  public sealed class Dialouge : Command
```suggestion
  public sealed class Dialogue : Command
```

2023-09-25 23:12 UTC, YakaryBovine commented on src/MacroTools/Commands/Captions.cs
> +    public override string Description => "Toggles the display of captions.";
Let's keep the language really simple for people.
```suggestion
    public override string Description => "Turns dialogue captions on or off.";
```

2023-09-25 23:12 UTC, YakaryBovine commented on src/MacroTools/Commands/Settings.cs
> +    public override string Description => "Shows the current settings for the player.";
```suggestion
    public override string Description => "Shows your current settings.";
```

2023-09-26 08:19 UTC, SavanticIO commented
Thanks. I’ve tested the loading, saving and a failed load. I haven’t tested the failedhash response. I think you would have to correctly deserialise, change a value and then serialise again but not 100% sure on that.

2023-09-26 10:33 UTC, YakaryBovine approved these changes
Awesome. Happy with this!

2023-09-26 10:33 UTC, merged