Technopig/crippling shout
AzerothWarsLR/WarcraftLegacies pull request #2293
Opened 2023-09-30 22:58 UTC by Technopig1992

2023-09-30 23:53 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/1329803368.json
> +      "Value": "Frostwolf Animal Tammer.|n|cfff5962dAbilities:|R Crippling Shout, War Cadence|n |n|cff99b4d1Can only train 2.|n|cffffcc00Attacks land and air units.|r"
Could we fix the typos while we're at it, apparently I missed them:
```suggestion
      "Value": "Frostwolf animal tamer.|n|cfff5962dAbilities:|R Crippling Shout, War Cadence|n |n|cff99b4d1Can only train 2.|n|cffffcc00Attacks land and air units.|r"
```

2023-10-01 00:01 UTC, YakaryBovine requested changes
Everything looks really solid aside from the fact that it applies Howl of Terror on top of Cripple. Please test that your Targets Allowed change worked then let me know.

2023-10-01 00:54 UTC, Technopig1992 commented
> Everything looks really solid aside from the fact that it applies Howl of Terror on top of Cripple. Please test that your Targets Allowed change worked then let me know.

Tested, will start making it a part of the practice going forward.  all working okay. its removing the AOE on the ability that avoids it

2023-10-01 01:26 UTC, YakaryBovine commented
Well done. Not quite there yet. With a range of 0, the ability can still target the caster. So:
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/9e3c49a8-7f52-41ac-9592-896bc96dbddd)
I would recommend changing Targets Allowed to Bridge or something.

2023-10-01 01:27 UTC, Technopig1992 commented
hmm didn't notice that ill make it cripple and it should be fine

2023-10-01 01:42 UTC, YakaryBovine requested changes
The last change has clearly not been tested and this is not ready for review.

2023-10-01 02:25 UTC, YakaryBovine approved these changes
Looking good.

2023-10-01 02:25 UTC, merged