Madsen/balance changes 3.8.7
AzerothWarsLR/WarcraftLegacies pull request #2376
Opened 2023-10-11 01:35 UTC by Ripzss

2023-10-11 02:30 UTC, Ripzss commented
Made it so Zandalari can now train their elites from Zul'farak

2023-10-12 02:20 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/909455471.json
> +      "Value": "Font of arcane power. Provides 8 food, which increases the maximum number of units that can be trained.|n|cfff5962dAbilities:|R Charge Mana|n|n|cff99b4d1Can only train 48"
This should still say "build", not "train". Buildings don't get trained.

2023-10-12 02:21 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/859189352.json
> +      "Value": "Font of Arcane energy.|nProvides 10 food, which increases the maximum number of units that can be trained.|n|r|n|cff99b4d1Can only build 48."
This should still say "build", not "train". Buildings don't get trained.

2023-10-12 02:23 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/859189352.json
> +      "Value": "Font of Arcane energy.|nProvides 10 food, which increases the maximum number of units that can be trained.|n|r|n|cff99b4d1Can only build 48."
Dalaran's farms have no build limit, so the "Can only build 48" bit is incorrect.

2023-10-12 02:23 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/859189352.json
> +      "Value": "Font of Arcane energy.|nProvides 10 food, which increases the maximum number of units that can be trained.|n|r|n|cff99b4d1Can only build 48."
No need to capitalize arcane; it's not a proper noun.

2023-10-12 04:04 UTC, YakaryBovine commented
There's a tonne of changes in here so it's a bit hard to review but I've done my best. Looks good, just still some issues with the Dalaran and Exodar Well tooltips. I know you didn't cause the issues I'm pointing out but that ticket can't be closed until the tooltip is actually correct.

2023-10-12 04:04 UTC, YakaryBovine requested changes
There's a tonne of changes in here so it's a bit hard to review but I've done my best. Looks good, just still some issues with the Dalaran and Exodar Well tooltips. I know you didn't cause the issues I'm pointing out but that ticket can't be closed until the tooltip is actually correct.

2023-10-12 22:33 UTC, YakaryBovine approved these changes
Looking good!

2023-10-12 22:33 UTC, merged