Hydromancer new E, Dreadlord spell fixes, New Ghoul spells
AzerothWarsLR/WarcraftLegacies pull request #2513
Opened 2023-10-25 04:14 UTC by SebastianTanoni

2023-10-25 19:28 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/3e0978e3-73ef-457f-a4d4-9f771909fb14)
Do you want the Ghoul to have this little bright orb on his hand?

2023-10-25 19:29 UTC, SebastianTanoni commented
> ![image](https://user-images.githubusercontent.com/8995690/278125066-3e0978e3-73ef-457f-a4d4-9f771909fb14.png) Do you want the Ghoul to have this little bright orb on his hand?

thats a good question. Do you think the passive is fine without a visual aid on the unit?

2023-10-25 20:18 UTC, YakaryBovine commented
> > ![image](https://user-images.githubusercontent.com/8995690/278125066-3e0978e3-73ef-457f-a4d4-9f771909fb14.png) Do you want the Ghoul to have this little bright orb on his hand?
> 
> thats a good question. Do you think the passive is fine without a visual aid on the unit? Since you worry more about visual clarity, i think you are better to answer! i can remove it if you think its unneded

Yeah I don't think it's needed; the light bulb doesn't really mean anything to players anyway, especially since no other unit shares it. I'd also be worried about special effect lag considering Ghouls can be spammed.

BTW I had to run to work before I could finish the review, that's not the whole thing 😆

2023-10-25 21:11 UTC, SebastianTanoni commented
Perfect, il remove the effect!

2023-10-25 23:17 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1431515201.json
> +      "Value": "Increases damage dealt to enemy targets with unarmored armor by \u003CA0SU,DataB1,%\u003E%."
```suggestion
      "Value": "Increases damage dealt to enemy targets with Unarmored armor by \u003CA0SU,DataB1,%\u003E%."
```

2023-10-25 23:22 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1465069633.json
> +      "Value": "Causes the Ghoul to keep fighting upon death, allowing it to continue fighting for 30 seconds. The Ghoul will be uncontrollable and invulnerable."
```suggestion
      "Value": "Upon death, the Ghoul becomes invulnerable and uncontrollable and continues fighting for 30 seconds."
```

2023-10-25 23:24 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/959590465.json
> +      "Value": "Summons a water elemental. Has \u003Ch00U,realHP\u003E hit points and deals \u003Ch00U,mindmg1\u003E - \u003Ch00U,maxdmg1\u003E damage. Can Learn the Freezing Shot ability. |nLasts \u
```suggestion
      "Value": "Summons a Water Elemental, which has \u003Ch00U,realHP\u003E hit points, deals \u003Ch00U,mindmg1\u003E - \u003Ch00U,maxdmg1\u003E damage, and can learn the Freezing Shot ability. |nLasts \u003CA029,Dur1\u003E seconds. Water Elementals are affected by the Power Infusion and Hydromancer Training researches.|n|n|cffffcc00Attacks land and air units.|r"
```

2023-10-25 23:27 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1278488641.json
> +      "Value": "Summon a Storm cloud at a target location. The Storm cloud will fire a lightning bolt every 2 seconds, dealing 50 damage to a random enemy. In addition, the Storm Cloud will deal \u00
```suggestion
      "Value": "Channels a Storm Cloud at the target location after casting for \u003CA04L,Cast1\u003E seconds. The Storm Cloud will fire a lightning bolt every 2 seconds, dealing 50 damage to a random enemy. In addition, the Storm Cloud will deal \u003CA0CZ,DataA1\u003E damage per second to nearby enemy air units.|nLasts \u003CA04L,Dur1\u003E seconds."
```

2023-10-25 23:31 UTC, YakaryBovine requested changes
Just some minor tooltip stuff to fix. Great otherwise.

Personally I'm not a fan of Undying Frenzy. I don't think a tier 1 unit should have 5 abilities, especially when none of them are gated behind researches. Between Ripping Claw, Charge, and Skeletal Frame, surely the unit has a concrete identity. 
The implementation is a bit iffy as well. Though the half-Ghoul model looks great and the uncontrollable aspect is thematic, because the unit still _looks_ like a unit, the mechanic just comes across as buggy-feeling to me. Does it need to be untargetable to work?
Your call on the ability anyway, just offering 2 cents. Only need to fix the tooltip issues for me to merge.

2023-10-26 04:04 UTC, SebastianTanoni commented
Todo: remove skeletal frame, remove locust aspect from undying frenzy

2023-10-26 04:55 UTC, YakaryBovine commented
Also, only just thought to check: Ripping Claws doesn't work. Tried attacking some Unarmored casters and it doesn't seem to change the Ghoul's damage.

2023-10-26 05:07 UTC, YakaryBovine commented
I double-checked the corpse thing for you; the answer is that neither the Ghoul nor the reanimated Ghoul leaves a corpse. The `SummonUnitOnDeath` trigger currently removes the dying unit, and I guess summoned units never leave behind corpses. So no corpse.

2023-10-26 20:20 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1278488641.json
> +      "Value": "Channels a Storm Cloud at the target location after casting for \u003CA04L,Cast1\u003E seconds. The Storm Cloud will attack a random enemy in range, dealing \u003Cn03J,maxdmg1\u003E c
```suggestion
      "Value": "Channels a Storm Cloud at the target location after casting for \u003CA04L,Cast1\u003E seconds. The Storm Cloud will attack nearby enemy units, dealing \u003Cn03J,maxdmg1\u003E Chaos damage with each attack. In addition, the Storm Cloud will deal \u003CA0CZ,DataA1\u003E damage per second to nearby enemy air units.|nLasts \u003CA04L,Dur1\u003E seconds."
```

2023-10-26 20:46 UTC, YakaryBovine approved these changes
Looking good!

2023-10-26 20:46 UTC, merged