Brigitte Abendis finished, all scarlet tech tree, tooltips, lategame quests and buildings finished
AzerothWarsLR/WarcraftLegacies pull request #2543
Opened 2023-10-28 19:29 UTC by SebastianTanoni

2023-10-28 21:26 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/bf32c1a3-4726-4fe0-8f7a-070b47e90403)
Can't upgrade to Keep.

2023-10-28 21:27 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/220eba49-a715-4a8e-a7e5-28169e8c0c41)
Can't upgrade Keep to Castle.

2023-10-28 21:29 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/ee56d73b-c892-455d-9145-7724ab1a8507)
Shows level 1 but there doesn't seem to be a way to get level 2.

2023-10-28 21:29 UTC, SebastianTanoni commented
> ![image](https://user-images.githubusercontent.com/8995690/278838624-ee56d73b-c892-455d-9145-7724ab1a8507.png) Shows level 1 but there doesn't seem to be a way to get level 2.

isnt it improved with the attack upgrades? i feel like thats how paladin works forever

2023-10-28 21:31 UTC, YakaryBovine commented
> > ![image](https://user-images.githubusercontent.com/8995690/278838624-ee56d73b-c892-455d-9145-7724ab1a8507.png) Shows level 1 but there doesn't seem to be a way to get level 2.
> 
> isnt it improved with the attack upgrades? i feel like thats how paladin works forever

Oh true, looks like that does work. I don't remember re-coding that in C#.

2023-10-28 21:31 UTC, YakaryBovine commented
Ensnare says level 1 but I can't get level 2.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/410413aa-d767-4a57-8708-333390acf99f)

2023-10-28 21:32 UTC, YakaryBovine commented
Can't build any buildings that require Town Hall even though I have a Town Hall.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/17e747cc-1180-468a-ae7d-676a8be12899)

2023-10-28 21:32 UTC, YakaryBovine commented
No ships in the Shipyard.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/e99bc978-22d1-4937-a5a2-763586af45cc)

2023-10-28 21:37 UTC, YakaryBovine commented
Unholy Archon should be in the "Can learn" category. Also should be Sanctify, not Holy Fire.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/93d7256f-eb92-4427-a366-dcd24aeb427c)

2023-10-28 21:42 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/827600961.json
> +      "Value": "Causes the Scarlet Bishop to transform into a Unholy Archon upon death, allowing it to continue fighting for 30 seconds."
```suggestion
      "Value": "Causes the Scarlet Bishop to transform into an Shadow Archon upon death, allowing it to continue fighting for 30 seconds. The Shadow Archon has a powerful Chaos attack and no abilities."
```

2023-10-28 21:42 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/827600961.json
> +      "Value": "Unholy Archon"
```suggestion
      "Value": "Shadow Archon"
```

2023-10-28 21:42 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/827600961.json
> +      "Value": "Unholy Archon"
```suggestion
      "Value": "Shadow Archon"
```

2023-10-28 21:43 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/745e8d35-7ab1-4580-b3f5-97385c4a205c)
As a limited caster, this should have Resistant Skin right?

2023-10-28 21:45 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/e4d8ced9-63a3-490e-b60e-6932c91cef5f)
Didn't even look but I bet this building doesn't have Druid of the Scythe training.

2023-10-28 21:46 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/1362702440.json
> +      "Value": "Scarlet commander.|n|cfff5962dAbilities:|R Charge, Deploy Trebuchet, United for the Cause, United for the Crusade|n|n|cff99b4d1Can only train 8|n|cffffcc00Attacks land units.|r"
```suggestion
      "Value": "Scarlet commander.|n|cfff5962dAbilities:|R Charge, Deploy Trebuchet, United for the Cause, United for the Crusade|n|n|cff99b4d1Can only train 8.|n|cffffcc00Attacks land units.|r"
```

2023-10-28 21:47 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/UnitData/Skin/1362702440.json
> +      "Value": "Scarlet commander.|n|cfff5962dAbilities:|R Charge, Deploy Trebuchet, United for the Cause, United for the Crusade|n|n|cff99b4d1Can only train 8|n|cffffcc00Attacks land units.|r"
```suggestion
      "Value": "Scarlet commander.|n|cfff5962dAbilities:|R Charge!, Deploy Trebuchet, United for the Cause, United for the Crusade|n|n|cff99b4d1Can only train 8.|n|cffffcc00Attacks land units.|r"
```

2023-10-28 21:48 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/4a086834-3280-45a1-8456-6bbacc4b4936)
Not a Hippogryph Rider nor a woman! Maybe just reword this to say "this unit", and change "her" to their so it's generic.

2023-10-28 21:49 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/2ea5e7a5-3d98-45f5-811b-a334091a7815)
Wrong limit, is actually 6.

2023-10-28 21:53 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/08b902e2-edc0-4a94-a5bf-8d41fe6dc704)
Missing Critical Strike.

2023-10-28 21:54 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/e63bc5db-fa28-447f-b7db-0b30f5e0b666)
Righteous Fury is just Pulverize and Retribution Aura is just Thorns Aura (actually it's even named Thorns Aura. If you want to keep it like this we'll need to rewrite our guidelines.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/26bd8775-8d65-4a61-b267-442dbf8072d3)

2023-10-28 21:55 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/d99b9271-dfad-4497-8095-6a14b9491ba3)
This Vendor-Hall has an inventory which is pretty pointless because if you try to put things in it, they just get sold.

2023-10-28 22:01 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/f6220893-17da-4285-8ef5-4b28269b4246)
No point having a Control Point level requirement of 1; might as well just be an objective to capture it.
Also need to add the Crimson Cathedral part to the reward description.

2023-10-28 22:02 UTC, YakaryBovine commented
Duration on Divine Intervention is too long, you can see the Scroll of Protection buff it gives. Probavbly just need to reduce it to 0.01: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/e8484802-bfb0-4214-a596-03b596cee472)

2023-10-28 22:04 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Brigitte complete abandonnement to vengance leads her to resetting all her abilities cooldown, but reducing her life regeneration rate by 10000% for 1 seconds.|n|n|cffffcc00Level 1|r
```suggestion
      "Value": "Resets the caster's ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|n|cffffcc00Level 1|r - 180 second cooldown.|n|cffffcc00Level 2|r - 140 second cooldown.|n|cffffcc00Level 3|r - 120 second cooldown.|n|cffffcc00Level 4|r - 100 second cooldown."
```

2023-10-28 22:04 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Brigitte complete abandonnement to vengance leads her to resetting all her abilities cooldown, but reducing her life regeneration rate by 10000% for 1 seconds.|n|cff99b4d1180 second c
```suggestion
      "Value": "Resets the caster's ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1180 second cooldown|r"
```

2023-10-28 22:04 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Brigitte complete abandonnement to vengance leads her to resetting all her abilities cooldown, but reducing her life regeneration rate by 10000% for 1 seconds.|n|cff99b4d1140 second c
```suggestion
      "Value": "Resets the caster's ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1140 second cooldown|r"
```

2023-10-28 22:04 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Brigitte complete abandonnement to vengance leads her to resetting all her abilities cooldown, but reducing her life regeneration rate by 10000% for 1 seconds.|n|cff99b4d1120 second c
```suggestion
      "Value": "Resets the caster's ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1120 second cooldown|r"
```

2023-10-28 22:04 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Brigitte complete abandonnement to vengance leads her to resetting all her abilities cooldown, but reducing her life regeneration rate by 10000% for 1 seconds.|n|cff99b4d1100 second c
```suggestion
      "Value": "Resets the caster's ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1100 second cooldown|r"
```

2023-10-28 22:06 UTC, YakaryBovine commented
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/632d9ea2-3a18-40bb-bb30-10865b8f26a4)
Requires a quest I can't complete.

2023-10-28 22:07 UTC, YakaryBovine requested changes
Honestly really well done, your attention to detail with this one was really solid. Just need to test with synergy on next time.

2023-10-29 00:27 UTC, SebastianTanoni commented
> ![image](https://user-images.githubusercontent.com/8995690/278839484-d99b9271-dfad-4497-8095-6a14b9491ba3.png) This Vendor-Hall has an inventory which is pretty pointless because if you try to put things in it, they just get sold.

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/75ca24ce-7a71-44e7-afe6-25967b74f59f)
It doesnt have an inventory ability

2023-10-29 03:34 UTC, YakaryBovine commented
Wrong research requirement: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/15050d31-b1cb-4db2-a7fa-87d1155f47fb)

2023-10-29 03:42 UTC, YakaryBovine commented
IIRC Madsen and Techno recently did some work on making sure heroes in Altars are organized by their level in ascending order, so Sally should be placed at the end:
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/637fa63d-49a9-4b6a-ae5f-f8bf3e1c4b50)

2023-10-29 03:43 UTC, YakaryBovine commented
Same issue with the Castle upgrade: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/56130394-637d-4f8d-b3e8-c320dccc028d)

2023-10-29 03:50 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1163210817.json
> +      "Value": "Restores 99999 hit points to friendly units in a large radius."
```suggestion
      "Value": "Fully heals all friendly units in a large radius."
```

2023-10-29 03:50 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1479562323.json
> +      "Value": "Calls a Divine Hammer down from the sky, dealing damage and stunning enemy land units in an area.   |n|n|cffffcc00Level 1|r - \u003CST0X,DataA1\u003E damage and stunning enemy land un
```suggestion
      "Value": "Calls a Divine Hammer down from the sky, dealing damage and stunning enemy land units in an area.   |n|n|cffffcc00Level 1|r - \u003CST0X,DataA1\u003E damage and stunning enemy land units for \u003CST0X,Dur1\u003E seconds.|n|cffffcc00Level 2|r -  \u003CST0X,DataA2\u003E damage and stunning enemy land units for \u003CST0X,Dur2\u003E seconds. |n|cffffcc00Level 3|r -  \u003CST0X,DataA3\u003E damage and stunning enemy land units for \u003CST0X,Dur3\u003E seconds."
```

2023-10-29 03:51 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|n|cffffcc00Level 1|r - 180 second cooldown.|n|cffffcc00Level 2|r - 140 s
```suggestion
      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 100 for 1 second.|n|n|cffffcc00Level 1|r - 180 second cooldown.|n|cffffcc00Level 2|r - 140 second cooldown.|n|cffffcc00Level 3|r - 120 second cooldown.|n|cffffcc00Level 4|r - 100 second cooldown."
```

2023-10-29 03:51 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1180 second cooldown|r"
```suggestion
      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 100 for 1 second.|n|cff99b4d1180 second cooldown|r"
```

2023-10-29 03:51 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1140 second cooldown|r"
```suggestion
      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 100 for 1 second.|n|cff99b4d1140 second cooldown|r"
```

2023-10-29 03:51 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1120 second cooldown|r"
```suggestion
      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 100 for 1 second.|n|cff99b4d1120 second cooldown|r"
```

2023-10-29 03:51 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1129590849.json
> +      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 10000% for 1 second.|n|cff99b4d1100 second cooldown|r"
```suggestion
      "Value": "Resets the caster\u0027s ability cooldowns, but reduces their life regeneration rate by 100 for 1 second.|n|cff99b4d1100 second cooldown|r"
```

2023-10-29 03:52 UTC, YakaryBovine requested changes
Just found a handful of other issues, all tiny.

2023-10-29 03:52 UTC, SebastianTanoni commented
> Just found a handful of other issues, all tiny.

Just fixed them and pushed!

2023-10-29 04:00 UTC, YakaryBovine approved these changes
Looks great!

2023-10-29 04:00 UTC, merged