Kalimdor Balance
AzerothWarsLR/WarcraftLegacies pull request #2901
Opened 2024-04-16 14:03 UTC by vampirika

**Druids:**

- Overall effective health of units reduced from between 11.25%-15% to 8%-10%. 
  - Reduce immortality chance 25% -> 20%.
  - Reduce immortality heal 45% -> 40%.
- Druid elite nova specific target damage down 50 -> ~40~ 35.
- Cenarius movespeed aura reduction down 6/12/18/24 -> 5/10/15/20.
- Druid starting goldmine value down 1000 -> 800.
- Mountain giants heal down 400 -> 250.

**Sents:**

- Archer barrage hero aim potential lower, but slightly better against groups.
  - Damage 50 -> 40
  - ~Max damage 200 -> 240~
  - AoE 100 -> 125
  - Cooldown 20 ->~40~ 30
- Elite movespeed ability down 25% -> 20%.
- CP aura movespeed down 24% -> ~10~ 15%.
- Naisha base health down 350 -> 200.
- Maeiv base health up 150 -> 250.
- First goldmine amount down 900 -> 800.
- Second goldmine amount down 800 -> 600.

**Draenei:**

- Velen movespeed aura down  5/10/15/20 -> 4/8/12/16.

Warsong:

- Grom health increased
  - Starting strength increased 22 -> 30.
  - Strength growth down 3.3 ->3.0.
  - Base health 240 -> 300.

**Frostwolf:**

- Thrall aura value increased 10% -> 20%.
- Doomhammer roar value decreased 50% -> 30%.

**General:**

- Zul'farrak movement speed aura up 10% -> 20%. _(tooltip was incorrect at 15%.)_

2024-04-16 15:49 UTC, SebastianTanoni commented
Nerf nova single target damage to 35

Barrage cooldown to 30

Barrage max damage stays the same

CP aura movespeed down 24% -> 10%. this is much too low for a unique mechanic

2024-04-16 21:24 UTC, YakaryBovine commented
Looks fantastic to me, but I'll test this in game before I merge.

2024-04-17 05:04 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1093742657.json
> +      "Value": "Warchief\u0027s Command"
This ability must be named "Command Aura" because it has the same effect as Command Aura.

2024-04-17 05:05 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1378955585.json
> +      "Value": "Gives nearby Sentinel units \u003CA11R,DataA1,%\u003E% movement speed increase."
Need to update the description of the Power too, it currently still says 24%: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/27d57d25-3cd5-4b47-abcc-326e118bff7a)

You can find it in line 180 of the Sentinels.cs file.

2024-04-17 05:06 UTC, YakaryBovine commented on mapdata/WarcraftLegacies/AbilityData/Skin/1244672083.json
> +      "Value": "Increases the movement speed of units by \u003CS00J,DataA1,%\u003E% in 5000 radius."
(Nitpick, optional) you could use data field referencing for the 5000 here too. It'd be something like <u003,Area1>.

2024-04-17 05:07 UTC, YakaryBovine requested changes
Tested everything, looks really robust, just a couple things to fix. Thanks for doing all the data field references!!

2024-04-17 21:28 UTC, YakaryBovine approved these changes
Noice

2024-04-17 21:28 UTC, merged